In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from json import dump
import gc

In [2]:
file = open("data/2020_public_lar_three_year_pipe.txt")

In [3]:
header = file.readline()
lines = file.readlines()

In [4]:
keys = [key for key in header.rstrip("\n").split("|")]
nas = np.zeros(len(keys))
for line in lines:
    line = line.rstrip("\n").split("|")
    for i, thing in enumerate(line):
        if thing == "NA" or thing == "":
            nas[i] += 1

In [5]:
file.close()

In [6]:
bad_idx = (nas / len(lines)) > 0.8

In [7]:
bad_idx

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False,  True,
        True,  True, False, False, False, False, False, False, False])

In [8]:
sample = np.random.binomial(1, 0.3, len(lines))

In [9]:
sample

array([0, 0, 0, ..., 0, 1, 0])

In [10]:
with open("data/csvlines.json", 'w') as file:
    dump(lines, file)

In [11]:
del lines

In [12]:
np.save("data/samples", sample)

In [13]:
bad_idx

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False,  True,
        True,  True, False, False, False, False, False, False, False])

In [14]:
file = open("data/2020_public_lar_three_year_pipe.txt")

In [15]:
data = {key: [] for key in np.array(keys)[~bad_idx]}
file.readline()
j = 0
while True:
    line = file.readline()
    if line == "":
        break
    if sample[j] == 1:
        line = line.rstrip("\n").split("|")
        for i, thing in enumerate(line):
            if bad_idx[i]:
                continue
            if thing == "":
                data[keys[i]].append("NA")
            else:
                data[keys[i]].append(thing)
    j += 1

In [16]:
file.close()

In [17]:
with open("data/initSample.json", 'w') as file:
    dump(data, file)

In [18]:
gc.collect()

32

In [19]:
newdat = pd.DataFrame.from_dict(data)

In [21]:
newdat.to_csv("data/train.csv")